
services:
  app:
    extends:
     file: docker-compose.yml
     service: app
    environment:
      - STAKING_STRATEGY_PROXY=0xb5B92DEFC0a9623E31e10Fe0BaE02610bf76fd09
      - STAKING_STRATEGY_VIEW=0x13eDDe0650E41f3B54E43f6783EA6eFD49F0C804
    env_file:
      - .env.hoodi
